name: build-dependencies

on:
  push:

jobs:
  vcpkg:
    name: build-${{ matrix.os }}-${{ matrix.package }}
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: 
          - ubuntu-latest
          # - macos-latest
          # - windows-latest
        package:
          - fmt
          - z3
          - capnproto
          - magic-enum
          - immer
    steps:
      - uses: actions/checkout@v2
        with:
          repository: microsoft/vcpkg
          ref: "2021.05.12"
          path: vcpkg

      - uses: actions/cache@v2
        with:
          path: |
            ~/vcpkg/vcpkg
          key: vcpkg-${{ runner.os }}-${{ hashFiles('vcpkg/.git/refs/HEAD') }}

      - name: Install vcpkg on linux
        if: ${{ matrix.os == 'ubuntu-latest' }}
        shell: bash
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
          echo "VCPKG_TRIPLET=x64-linux" >> $GITHUB_ENV
          
      - name: Install vcpkg on macos
        if: ${{ matrix.os == 'macos-latest' }}
        shell: bash
        run: |
          ./vcpkg/bootstrap-vcpkg.sh -disableMetrics
          echo "VCPKG_TRIPLET=x64-osx" >> $GITHUB_ENV
      
      - name: Install vcpkg on windows
        if: ${{ matrix.os == 'windows-latest' }}
        shell: bash
        run: |
          ./vcpkg/bootstrap-vcpkg.bat -disableMetrics
          echo "VCPKG_TRIPLET=x64-windows" >> $GITHUB_ENV 

      - name: Install ${{ matrix.package }}
        shell: bash
        run: |
          ./vcpkg/vcpkg install --triplet=${{ env.VCPKG_TRIPLET }} ${{ matrix.package }}
          ./vcpkg/vcpkg export  --triplet=${{ env.VCPKG_TRIPLET }} ${{ matrix.package }} \
            --output-dir=. \
            --output=${{ matrix.package }} \
            --raw

          tar c ${{ matrix.package }} | xz -4e > ${{ matrix.package }}.tar.xz

      - uses: actions/upload-artifact@v2
        with:
          name: ${{ matrix.package }}-${{ matrix.os }}.tar.xz
          path: ${{ matrix.package }}.tar.xz